### ISSUE TITLE
Trophies/Prizes

### ISSUE THREAD

**Issue by DaveWeimer** [edreamleo/Go-Congress-2019#10]
**Update: EKR**

The plan is to have 4 trophies, and 92 certificates.  I'll look at what Office Max has. Total Awards has plenty of certificate holders. Process:
- Total Awards coordinates everything using email.
- Total Awards does everything on a cash basis.
- We'll need a ES number (501c3) to avoid sales tax.
Contact: Katie Moran, Total Awards, 833-1716.

**Dave's Original Comments**

In an ideal world, I think we would like to be able to present name-engraved trophies to tournament winners at the banquet. However, it is not feasible to have engraving done on such short notice. At the 1991 Congress, we printed certificates with names to distribute at the banquet, which was feasible because we set up the printing so that all we had to do was add names and apply a seal with a stamping device. To support vendors, winners also usually receive some gift certificates.

How should we proceed? Some options:

1. Generic trophies (event specific but without names)
2. Have trophies engraved but mail them to participants after event---overseas participants as well?
3. Print certificates with names to distribute at banquet
4. Generic trophies and certificates
5. Something else

**Comment by edreamleo** [comment]
On Fri, Dec 1, 2017 at 8:41 AM, DaveWeimer <notifications@github.com> wrote:

> In an ideal world, I think we would like to be able to present
> name-engraved trophies to tournament winners at the banquet. However, it is
> not feasible to have engraving done on such short notice. At the 1991
> Congress, we printed certificates with names to distribute at the banquet,
> which was feasible because we set up the printing so that all we had to do
> was add names and apply a seal with a stamping device. To support vendors,
> winners also usually receive some gift certificates.
>
> How should we proceed? Some options:
>
>    1. Generic trophies (event specific but without names)
>    2. Have trophies engraved but mail them to participants after
>    event---overseas participants as well?
>    3. Print certificates with names to distribute at banquet
>    4. Generic trophies and certificates
>    5. Something else
>
> ​#1 Is the simplest thing that could possibly work. I suspect it is the
standard operating procedures for most competitive events.  We could check
the trophy case at West High :-)

Edward

**Comment by edreamleo** [comment]
A rough count, sufficient for bids.

 U.S. Open: Figure no more than 30 bands: so at least 60 (if we do first and second place) but 90 if we were to do first, second, and third.

Self-Paired: 7
Lightning: 4
9x9: 4
13x13: 4
Senior: 2
Women: 2
Die Hard: 2
Master’s: 2 (maybe: not sure as we give a cash prize)

**Total** 85 if we go with only first and second in the U.S. open. 

(I think we can also give some gift certificates, which are subsidized by the vendors, to third places.)

 It would be ideal to have the Congress logo on the trophy. In terms of lettering, I think the Open second place would have the most letters:
```
2019 U.S. Open
23 Kyu Section
Second Place
```
Or maybe:
```
2019 U.S. Open
23 Kyu Section
2nd Place
```

If the Logo is on the trophy, then we don’t need 2019.

 We only have $1000 budgeted for all the trophies, but I would be happy to throw in another $500 if that makes a difference in quality.

 When it actually comes to ordering, we might want the Conference Center to place the order so we don’t pay sales tax.

**Comment by edreamleo** [comment]
Here is the list, for entry into the DB:

US Open
6 Dan section
First place

US Open
6 Dan section
Second place

US Open
5 Dan section
First place

US Open
5 Dan section
Second place

US Open
4 Dan section
First place

US Open
4 Dan section
Second place

US Open
3 Dan section
First place

US Open
3 Dan section
Second place

US Open
2 Dan section
First place

US Open
2 Dan section
Second place

US Open
1 Dan section
First place

US Open
1 Dan section
Second place

US Open
1 Kyu section
First place

US Open
1 Kyu section
Second place

US Open
2 Kyu section
First place

US Open
2 Kyu section
Second place

US Open
3 Kyu section
First place

US Open
3 Kyu section
Second place

US Open
4 Kyu section
First place

US Open
4 Kyu section
Second place

US Open
5 Kyu section
First place

US Open
5 Kyu section
Second place

US Open
6 Kyu section
First place

US Open
6 Kyu section
Second place

US Open
7 Kyu section
First place

US Open
7 Kyu section
Second place

US Open
8 Kyu section
First place

US Open
8 Kyu section
Second place

US Open
9 Kyu section
First place

US Open
9 Kyu section
Second place

US Open
10 Kyu section
First place

US Open
10 Kyu section
Second place

US Open
11 Kyu section
First place

US Open
11 Kyu section
Second place

US Open
12 Kyu section
First place

US Open
12 Kyu section
Second place

US Open
13 Kyu section
First place

US Open
13 Kyu section
Second place

US Open
14 Kyu section
First place

US Open
14 Kyu section
Second place

US Open
15 Kyu section
First place

US Open
15 Kyu section
Second place

US Open
16 Kyu section
First place

US Open
16 Kyu section
Second place

US Open
17 Kyu section
First place

US Open
17 Kyu section
Second place

US Open
18 Kyu section
First place

US Open
18 Kyu section
Second place

US Open
19 Kyu section
First place

US Open
19 Kyu section
Second place

US Open
20 Kyu section
First place

US Open
20 Kyu section
Second place

US Open
21 Kyu section
First place

US Open
21 Kyu section
Second place

US Open
22 Kyu section
First place

US Open
22 Kyu section
Second place

US Open
23 Kyu section
First place

US Open
23 Kyu section
Second place

US Open
24 Kyu section
First place

US Open
24 Kyu section
Second place

US Open
25 Kyu and below section
First place

US Open
25 Kyu and below section
Second place

Self Paired Tournament
Dedicated: Most games
First place

Self Paired Tournament
Dedicated: Most games
Second place

Self Paired Tournament
Hurricane: Most wins
First place

Self Paired Tournament
Hurricane: Most wins
Second place

Self Paired Tournament
Kyu Killer
First place

Self Paired Tournament
Kyu Killer
Second place

Self Paired Tournament
Dan Slayer
First place

Self Paired Tournament
Dan Slayer
Second place

Self Paired Tournament
Sensei
First place

Self Paired Tournament
Sensei
Second place

Self Paired Tournament
Stoned
First place

Self Paired Tournament
Stoned
Second place

Self Paired Tournament
Philanthropist
First place

Self Paired Tournament
Philanthropist
Second place

Lighting Tournament
Dan Section
First Place

Lighting Tournament
Dan Section
Second Place

Lighting Tournament
Kyu Section
First Place

Lighting Tournament
Kyu Section
Second Place

9 x 9 Tournament
Dan Section
First Place

9 x 9  Tournament
Dan Section
Second Place

9 x 9  Tournament
Kyu Section
First Place

9 x 9  Tournament
Kyu Section
Second Place

13 x 13 Tournament
Dan Section
First Place

13 x 13  Tournament
Dan Section
Second Place

13 x 13 Tournament
Kyu Section
First Place

13 x 13 Tournament
Kyu Section
Second Place

Senior Tournament
First Place

Senior Tournament
Second Place

Women's Tournament
First Place

Women's Tournament
Second Place

Die Hard Tournament
First Place

Die Hard Tournament
Second Place

Master's Tournament
First Place

Master's Tournament
Second Place
