### ISSUE TITLE
Major tasks

### ISSUE THREAD

**Issue by edreamleo** [edreamleo/Go-Congress-2019#4]
Here are some of the major tasks to be accomplished:

- [ ] **Important**: Set up go boards before the Congress.
    - [ ] Find a place to store the boards after the 2018 Congress.
- [ ] **Important**: Coordinate with UW:
    - [ ] Negotiate prices of all services and accommodations.
    - [ ] Finalize accommodations for attendees and pros.
    - [ ] Make sure affordable parking is available.
    - [ ] Inquire about medical needs.
- [ ] Promotion and sponsors:
    - [ ] Video of the Union.
    - [ ] Contract Wisconsin ginseng and cranberry growers.
    - [ ] Contact local restaurants.  Can they offer deals?
- [ ] Keep the pros happy
- [ ] Set up Wednesdays tours and events:
    - [ ] Have the Japanese prints at the Chazen be on exhibit.
    - [ ] Tours of the Capital.

**Comment by DaveWeimer** [comment]
Hi Edward,

Testing.

Best,
Dave

**Comment by edreamleo** [comment]
@DaveWeimer Yes.  I see the test.

**Comment by DaveWeimer** [comment]
Two urgent things for the beginning of 2018:

1. Figure out logo---Dave will try contacting design class one more time after exam period
2. Try to recruit Phil Straus to produce a promotional video in early summer so we can show it at the 2018 Congress.

**Comment by edreamleo** [comment]
On Wed, Dec 20, 2017 at 3:34 PM, DaveWeimer <notifications@github.com>
wrote:

> Two urgent things for the beginning of 2018:
>
>    1. Figure out logo---Dave will try contacting design class one more
>    time after exam period
>    2. Try to recruit Phil Straus to produce a promotional video in early
>    summer so we can show it at the 2018 Congress.
>
> ​I'll volunteer for this.


Edward

**Comment by DaveWeimer** [comment]
Great! Enjoy your travels. Best, D.

David L. Weimer
Edwin E. Witte Professor of Political Economy
Robert M. La Follette School of Public Affairs and
Department of Political Science
University of Wisconsin-Madison
1225 Observatory Drive
Madison WI 53706
Tel: (608) 263-2325; FAX: (608) 265-3233
http://www.lafollette.wisc.edu/

[cid:image001.png@01D37A51.6078B760]
www.cambridge.org/9781316647660<http://www.cambridge.org/9781316647660>
