### ISSUE TITLE
Documents

### ISSUE THREAD

**Issue by DaveWeimer** [edreamleo/Go-Congress-2019#7]
[Event_Sketch_US_Go_Congress.pdf](https://github.com/edreamleo/Go-Congress-2019/files/1499619/Event_Sketch_US_Go_Congress.pdf)
[USGC Test Budget 2019.xlsx](https://github.com/edreamleo/Go-Congress-2019/files/1499621/USGC.Test.Budget.2019.xlsx)
[USGC 2019 UWM Meeting Notes 9152017-2CK comments.docx](https://github.com/edreamleo/Go-Congress-2019/files/1499624/USGC.2019.UWM.Meeting.Notes.9152017-2CK.comments.docx)
[Go Congress Contract.pdf](https://github.com/edreamleo/Go-Congress-2019/files/1499625/Go.Congress.Contract.pdf)
[Go conference host letter.pdf](https://github.com/edreamleo/Go-Congress-2019/files/1499626/Go.conference.host.letter.pdf)

**Comment by DaveWeimer** [comment]
[USGC 2019 Meeting Notes 9152017.docx](https://github.com/edreamleo/Go-Congress-2019/files/1499629/USGC.2019.Meeting.Notes.9152017.docx)

**Comment by edreamleo** [comment]
Glad to see you are up to speed, Dave.
