### ISSUE TITLE
Congress Logo

### ISSUE THREAD

**Issue by DaveWeimer** [edreamleo/Go-Congress-2019#8]
I think we want a simple design with some Wisconsin or Madison content for the Congress logo.

Last week I sent an e-mail to Lesley Sager, who teaches design in the School of Human Ecology, asking if there might be a possibility for a design competition in a relevant class. (Offered a $100 prize from my own funds.) Haven't heard back yet. Will follow-up before the end of the semester. If a class project isn't feasible, then we should think of ways we might do the design ourselves.

**Comment by edreamleo** [comment]
On Tue, Nov 28, 2017 at 9:16 AM, DaveWeimer <notifications@github.com>
wrote:

> I think we want a simple design with some Wisconsin or Madison content for
> the Congress logo.
>
​Good idea.

Edward

**Comment by DaveWeimer** [comment]
So far I haven't been able to set up a design competition. If forced to sketch a design today, here is what it would look like:

The background would be a map of the Madison Isthmus with water in blue and land a tan with go board lines, On the left would be a ponukki in what stones. The four white stones would have Go in Japanese, Chinese, Korean, and English. On the right would be 2019 US Go Congress, Madison, WI.

Thoughts? Do you have any software that would allow us to try to implement something like this ourselves?
